### ISSUE TITLE
KeyError: 'Unable to open object (free block size is zero?)'

### ISSUE THREAD

**Issue by aaon22357** [huaifeng1993/FashionAI_Key_Points_Detection#9]
很抱歉打扰您，我在运行single_train.py文件时，发现找不到验证集，自己随机切分出来一部分训练图片作为验证集后，遇到如下错误：

```
Train Images: 16631

Valid Images: 187
Traceback (most recent call last):
  File "single_train.py", line 299, in <module>
    model.load_weights(SELF_MODEL_PATH, by_name=True)
  File "/media/zww/要记得拔硬盘/tianchi/code/model.py", line 2817, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, layers)
  File "/home/zww/Software/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/keras/engine/saving.py", line 974, in load_weights_from_hdf5_group_by_name
    g = f[name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/zww/Software/anaconda3/envs/tensorflow-gpu/lib/python3.5/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (free block size is zero?)'
```
请问您知道如何解决吗？谢谢。

**Comment by huaifeng1993** [comment]
抱歉，不知怎么收不到git的邮件了， 在 single_train.py中这这几行代码是生成训练集和验证集的。可以先试一下这几行代码是否可以正常加载图片。
```
    dataset_train = FIDataset()
    dataset_train.load_FI(category='train')
    dataset_train.prepare()

    # Validation dataset
    dataset_val = FIDataset()
    dataset_val.load_FI(category='val')
    dataset_val.prepare()
```

**Comment by aaon22357** [comment]
@huaifeng1993  这个其实是不行的，因为我从官网下载的数据集是没有验证集的，请问您是怎样划分训练和验证集的呢？我是在训练数据里随机选取了一部分图片用来做验证集（但并没有将验证集图片和注释单独挑出来，它仍和训练集混在一起，因此我修改了您的代码，就导致这样的错误了。

**Comment by huaifeng1993** [comment]
自己划分验证集和数据集，只需要修改single_train.py FIDataset这个类。可以在读取annotation后把index打乱后直接切片。例如我读取10000个annotation后，利用   
```
 indices = np.random.permutation(annotations.shape[0])
 annotations = annotations.iloc[indices]
train_annotations=annotations [:9000]
val_annotations=annotations[9000:]
```
去切分数据集。这样可以避免，验证集存于训练集中。我只是粗略的写了一下代码，具体的逻辑你可以在FIDataset.load_FI()函数中实现。

**Comment by aaon22357** [comment]
@huaifeng1993  感谢您的回复，给了我很大启发，谢谢您！
